// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AvatarUploadController from "./avatar_upload_controller"
application.register("avatar-upload", AvatarUploadController)

import CounterController from "./counter_controller"
application.register("counter", CounterController)

import FieldFillController from "./field_fill_controller"
application.register("field-fill", FieldFillController)

import FileUploadController from "./file_upload_controller"
application.register("file-upload", FileUploadController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import ImageLoaderController from "./image_loader_controller"
application.register("image-loader", ImageLoaderController)

import ImagePreviewController from "./image_preview_controller"
application.register("image-preview", ImagePreviewController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import SearchFormController from "./search_form_controller"
application.register("search-form", SearchFormController)

import SlimSelectController from "./slim_select_controller"
application.register("slim-select", SlimSelectController)
