require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - log/**/*
    - public/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
    - config.ru
    - Gemfile
    - Rakefile
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 80
Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument
Layout/BlockAlignment:
  EnforcedStyleAlignWith: start_of_block
Layout/FirstArgumentIndentation:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
Rails/ActionOrder:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/InverseOf:
  Enabled: false
