require:
  - rubocop-rails
  - rubocop-rspec

plugins:
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - db/schema.rb
    - log/**/*
    - public/**/*
    - storage/**/*
    - tmp/**/*
    - vendor/**/*
    - config.ru
    - Gemfile
    - Rakefile
  Include:
    - '**/*.rb'
    - '**/*.gemfile'
    - '**/*.gemspec'
    - '**/*.rake'
    - '**/*.ru'
    - '**/Gemfile'
    - '**/Rakefile'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false
Rails/ActionOrder:
  Enabled: false
Rails/UniqueValidationWithoutIndex:
  Enabled: false
Rails/InverseOf:
  Enabled: false
