default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: booking_app_development

test:
  <<: *default
  database: booking_app_test

production:
  <<: *default
  database: book_my_show_production
  username: book_my_show
  password: <%= ENV["BOOK_MY_SHOW_DATABASE_PASSWORD"] %>
